export const dairyProducts = [
  {
    value: "AMF",
    label: "ANHYDROUS MILK FAT",
    id: 15473,
    commodityType: "D",
  },
  {
    value: "CHD",
    label: "CHEDDAR CHEESE",
    id: 17473,
    commodityType: "D",
  },
  {
    value: "CRE",
    label: "CREAM",
    id: 18673,
    commodityType: "D",
  },
  {
    value: "GHE",
    label: "GHEE",
    id: 23073,
    commodityType: "D",
  },
  {
    value: "GMC",
    label: "GOAT MILK CHEESE",
    id: 23473,
    commodityType: "D",
  },
  {
    value: "SMY",
    label: "SHEEP MILK YOGHURT",
    id: 28673,
    commodityType: "D",
  },
  {
    value: "UHC",
    label: "UHT CREAM AND CREAM PRODUCTS",
    id: 29073,
    commodityType: "D",
  },
  {
    value: "CBP",
    label: "CREAM BASED POWDER",
    id: 17073,
    commodityType: "D",
  },
  {
    value: "DML",
    label: "MILK POWDER",
    id: 19673,
    commodityType: "D",
  },
  {
    value: "DSP",
    label: "DAIRY STOCKFOOD POWDER",
    id: 20473,
    commodityType: "D",
  },
  {
    value: "UHT",
    label: "UHT MILK AND MILK PRODUCTS",
    id: 29273,
    commodityType: "D",
  },
  {
    value: "BMC",
    label: "BUFFALO MILK CHEESE",
    id: 15673,
    commodityType: "D",
  },
  {
    value: "CAS",
    label: "CASEIN",
    id: 16673,
    commodityType: "D",
  },
  {
    value: "CML",
    label: "CONDENSED MILK",
    id: 18073,
    commodityType: "D",
  },
  {
    value: "DES",
    label: "DAIRY DESSERTS",
    id: 19073,
    commodityType: "D",
  },
  {
    value: "ECD",
    label: "EU COMPOSITE DAIRY PRODUCTS",
    id: 20873,
    commodityType: "D",
  },
  {
    value: "HCH",
    label: "HARD CHEESE",
    id: 24673,
    commodityType: "D",
  },
  {
    value: "SMP",
    label: "SHEEP MILK POWDER",
    id: 28473,
    commodityType: "D",
  },
  {
    value: "BMI",
    label: "BUFFALO MILK",
    id: 15873,
    commodityType: "D",
  },
  {
    value: "DTG",
    label: "DAIRY TECHNICAL GRADE",
    id: 20673,
    commodityType: "D",
  },
  {
    value: "FZC",
    label: "FREEZE DRIED CAMEL MILK",
    id: 22473,
    commodityType: "D",
  },
  {
    value: "GMK",
    label: "UHT GOAT MILK",
    id: 23673,
    commodityType: "D",
  },
  {
    value: "ICE",
    label: "ICECREAM",
    id: 24873,
    commodityType: "D",
  },
  {
    value: "PCH",
    label: "PROCESSED CHEESE",
    id: 27073,
    commodityType: "D",
  },
  {
    value: "SMC",
    label: "SHEEP MILK CHEESE",
    id: 28073,
    commodityType: "D",
  },
  {
    value: "VHC",
    label: "VERY HARD CHEESE",
    id: 29673,
    commodityType: "D",
  },
  {
    value: "WHE",
    label: "WHEY",
    id: 30073,
    commodityType: "D",
  },
  {
    value: "YSP",
    label: "YOGHURT SOFT SERVE POWDER",
    id: 30473,
    commodityType: "D",
  },
  {
    value: "FCH",
    label: "FRESH CHEESE",
    id: 21473,
    commodityType: "D",
  },
  {
    value: "GIF",
    label: "GOAT MILK INFANT FORMULA",
    id: 23273,
    commodityType: "D",
  },
  {
    value: "GOS",
    label: "GALACTO-OLIGOSACCHARIDE",
    id: 24273,
    commodityType: "D",
  },
  {
    value: "NPG",
    label: "NON-PRESCRIBED GOODS",
    id: 26873,
    commodityType: "D",
  },
  {
    value: "WEY",
    label: "WHEY POWDER",
    id: 29873,
    commodityType: "D",
  },
  {
    value: "YOG",
    label: "YOGHURT",
    id: 30273,
    commodityType: "D",
  },
  {
    value: "DMP",
    label: "MILK PROTEIN CONCENTRATE",
    id: 19873,
    commodityType: "D",
  },
  {
    value: "FDP",
    label: "FLAVOURED DRINKING POWDER",
    id: 21673,
    commodityType: "D",
  },
  {
    value: "MEM",
    label: "MEMBRANE & ULTRA FILTRATION PRODUCT",
    id: 26073,
    commodityType: "D",
  },
  {
    value: "PSD",
    label: "PROTEIN SUPPLEMENT DRINK",
    id: 27273,
    commodityType: "D",
  },
  {
    value: "SCH",
    label: "SOFT CHEESE",
    id: 27473,
    commodityType: "D",
  },
  {
    value: "SHC",
    label: "SEMI HARD CHEESE",
    id: 27673,
    commodityType: "D",
  },
  {
    value: "BUT",
    label: "BUTTER",
    id: 16273,
    commodityType: "D",
  },
  {
    value: "CAM",
    label: "CAMEL MILK",
    id: 16473,
    commodityType: "D",
  },
  {
    value: "CCH",
    label: "CANNED CHEESE",
    id: 17273,
    commodityType: "D",
  },
  {
    value: "COP",
    label: "COLOSTRUM POWDER",
    id: 18473,
    commodityType: "D",
  },
  {
    value: "DSA",
    label: "DAIRY BASED SAUCES",
    id: 20073,
    commodityType: "D",
  },
  {
    value: "DSL",
    label: "DAIRY STOCKFOOD LIQUID",
    id: 20273,
    commodityType: "D",
  },
  {
    value: "INF",
    label: "INFANT POWDER",
    id: 25073,
    commodityType: "D",
  },
  {
    value: "LAC",
    label: "LACTOFERRIN",
    id: 25273,
    commodityType: "D",
  },
  {
    value: "MIL",
    label: "MILK",
    id: 26273,
    commodityType: "D",
  },
  {
    value: "BMY",
    label: "BUFFALO MILK YOGHURT",
    id: 16073,
    commodityType: "D",
  },
  {
    value: "CHP",
    label: "CHEESE POWDER",
    id: 17673,
    commodityType: "D",
  },
  {
    value: "CSC",
    label: "CASEINATE",
    id: 18873,
    commodityType: "D",
  },
  {
    value: "FZD",
    label: "FREEZE DRIED DAIRY PRODUCTS",
    id: 22673,
    commodityType: "D",
  },
  {
    value: "GMP",
    label: "GOAT MILK POWDER",
    id: 23873,
    commodityType: "D",
  },
  {
    value: "GMY",
    label: "GOAT MILK YOGHURT",
    id: 24073,
    commodityType: "D",
  },
  {
    value: "MLC",
    label: "MILK CONCENTRATE",
    id: 26473,
    commodityType: "D",
  },
  {
    value: "SMK",
    label: "SHEEP MILK",
    id: 28273,
    commodityType: "D",
  },
  {
    value: "SSP",
    label: "SOFT SERVE POWDER",
    id: 28873,
    commodityType: "D",
  },
];
